# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('degree', models.CharField(choices=[('BSc', 'Bachelor'), ('MS', 'Masters')], default='BSc', max_length=5)),
                ('topic', models.CharField(max_length=120)),
            ],
        ),
    ]
