# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('study_area', models.CharField(max_length=255)),
                ('office', models.CharField(max_length=255)),
                ('projects', models.ManyToManyField(to='web.Project')),
            ],
        ),
    ]
