# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_counselor'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='account_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
