# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-14 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_counselor_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='account_id',
            field=models.IntegerField(default=-1),
        ),
    ]
