# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-20 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20160314_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='url',
            field=models.URLField(default='NOURL'),
        ),
    ]
