# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_counselor_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=50),
        ),
    ]
