# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-09 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_counselor_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counselor',
            old_name='account_id',
            new_name='accountId',
        ),
        migrations.RenameField(
            model_name='counselor',
            old_name='study_area',
            new_name='studyArea',
        ),
    ]
